### ISSUE TITLE
Evaluate rotational speed and acceleration constants

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/ev3sim#85]
Possibly too fast at the moment

**Comment by peter-drew** [comment]
I think especially of the ball

**Comment by peter-drew** [comment]
Happy to take suggestions on values and either resolve or close relatively quickly.

**Comment by glipR** [comment]
re: ball, are you concerned with rotational acceleration or just general friction? I haven't noticed the ball rotating, since its a solid red :/

The angular and normal velocity are dampened by me in ev3sim/objects/base.py line 121->125, so you can play around with the constants mentioned there + add your own to fine tune the rotational speeds.

**Comment by peter-drew** [comment]
> re: ball, are you concerned with rotational acceleration or just general friction?

General friction. I'll take a look.
